### ISSUE TITLE
Does SLD support multiple cloud provider when operates resource on multiple cloud in one tf config ?

### ISSUE THREAD

**Issue by dehengxu** [D10S0VSkY-OSS/Stack-Lifecycle-Deployment#224]
May be is select multiple Squad in SLD

**Comment by dehengxu** [comment]
May I inject GCP, Azure Squad in one custom squad configuration?

**Comment by D10S0VSkY-OSS** [comment]
Hi @dehengxu,
You cannot use multiple squads in a Terraform deployment, but you can use multiple accounts in a squad using a custom type account. For GCP, I haven't had the chance to verify this. You can check out https://stackoverflow.com/questions/62491106/how-to-store-gcp-service-account-json-in-a-terrafrom-variable.

I'll try to test it and let you know ASAP. If you do it before me, please share it. P.S.: In the upcoming releases, it will be possible to add more than one account per squad (Work in Progress).
Regards

**Comment by dehengxu** [comment]
May be I have missunderstood, do you mean SLD one squad stand for one cloud provider ?

PS:

I need create k8s svc on multiple cloud providers, I have tried, in one terraform configuration which could use mulitple cloud providers to create resource, and it makes task simple and powerfull if SLD supported in future.

**Comment by D10S0VSkY-OSS** [comment]
Hi @dehengxu 
A 'squad' and 'environment' typically represents an account in AWS, a subscription in Azure, or a project in GCP. Generally, the accounts | subscription | project are associated with a squad (team) and an environment, for example, dev | pre | pro. Right now, SLD only supports one-to-one, except for 'custom' since you can pass it any parameters you want, so you can pass several accounts. Although, we will soon release a feature that will support the possibility of adding more accounts, even from different cloud providers
Regards

**Comment by dehengxu** [comment]
Awaiting new features

**Comment by dehengxu** [comment]
Thanks very much for your work

**Comment by dehengxu** [comment]
After looking up documents of cloud providers, Azure GCP support bind one ServiceAccount(Some equivalant concept between clouds) to multiple subscriptions or projects.

**Comment by dehengxu** [comment]
https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-cli#assign-role-examples

> I missremembered :(, it's only cross multiple subscritpions in one cloud provider ServicePrincipal, not cross multiple providers
